# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class Medicine:
    class BodyPart(SPGTypeHelper):

        id = PropertyHelper("id")
        description = PropertyHelper("description")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        name = PropertyHelper("name")

    class Disease(SPGTypeHelper):
        class abnormal(RelationHelper):
            range = PropertyHelper("range")
            shape = PropertyHelper("shape")
            color = PropertyHelper("color")

        id = PropertyHelper("id")
        commonSymptom = PropertyHelper("commonSymptom")
        description = PropertyHelper("description")
        diseaseSite = PropertyHelper("diseaseSite")
        complication = PropertyHelper("complication")
        applicableDrug = PropertyHelper("applicableDrug")
        department = PropertyHelper("department")
        name = PropertyHelper("name")

        abnormal = abnormal("abnormal")

    class Drug(SPGTypeHelper):

        id = PropertyHelper("id")
        description = PropertyHelper("description")
        name = PropertyHelper("name")

    class HospitalDepartment(SPGTypeHelper):

        id = PropertyHelper("id")
        description = PropertyHelper("description")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        name = PropertyHelper("name")

    class Indicator(SPGTypeHelper):

        id = PropertyHelper("id")
        description = PropertyHelper("description")
        name = PropertyHelper("name")

    class Symptom(SPGTypeHelper):

        id = PropertyHelper("id")
        description = PropertyHelper("description")
        name = PropertyHelper("name")

    BodyPart = BodyPart("Medicine.BodyPart")
    Disease = Disease("Medicine.Disease")
    Drug = Drug("Medicine.Drug")
    HospitalDepartment = HospitalDepartment("Medicine.HospitalDepartment")
    Indicator = Indicator("Medicine.Indicator")
    Symptom = Symptom("Medicine.Symptom")

    pass
