# -*- coding: utf-8 -*-
# Copyright 2023 Ant Group CO., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper


class Financial:
    
    class AdministrativeArea(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    class AreaRiskEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        subject = PropertyHelper("subject")
        object = PropertyHelper("object")
        eventTime = PropertyHelper("eventTime")
    
    class Company(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        orgCertNo = PropertyHelper("orgCertNo")
        regCapital = PropertyHelper("regCapital")
        legalPerson = PropertyHelper("legalPerson")
        regArea = PropertyHelper("regArea")
        establishDate = PropertyHelper("establishDate")
        businessScope = PropertyHelper("businessScope")
    
    class CompanyEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        eventTime = PropertyHelper("eventTime")
        subject = PropertyHelper("subject")
        location = PropertyHelper("location")
        happenedTime = PropertyHelper("happenedTime")
        object = PropertyHelper("object")
    
    class Indicator(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    class State(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        derivedFrom = PropertyHelper("derivedFrom")
        causes = PropertyHelper("causes")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
    
    AdministrativeArea = AdministrativeArea("Financial.AdministrativeArea")
    AreaRiskEvent = AreaRiskEvent("Financial.AreaRiskEvent")
    Company = Company("Financial.Company")
    CompanyEvent = CompanyEvent("Financial.CompanyEvent")
    Indicator = Indicator("Financial.Indicator")
    State = State("Financial.State")
    