# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

class Financial:
	def __init__(self):
		self.Indicator = self.Indicator()
		self.State = self.State()

	class Indicator:
		__typename__ = "Financial.Indicator"
		description = "description"
		id = "id"
		name = "name"
		alias = "alias"
		stdId = "stdId"

		def __init__(self):
			pass

	class State:
		__typename__ = "Financial.State"
		description = "description"
		id = "id"
		name = "name"
		stdId = "stdId"
		derivedFrom = "derivedFrom"
		causeOf = "causeOf"
		alias = "alias"

		def __init__(self):
			pass

