# coding: utf-8
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.


"""
    knext

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from knext.common.rest.configuration import Configuration


class VertexMatchRule(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "prop_filters": "list[PropertyFilter]",
        "return_props": "list[str]",
    }

    attribute_map = {"prop_filters": "propFilters", "return_props": "returnProps"}

    def __init__(
        self, prop_filters=None, return_props=None, local_vars_configuration=None
    ):  # noqa: E501
        """VertexMatchRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._prop_filters = None
        self._return_props = None
        self.discriminator = None

        if prop_filters is not None:
            self.prop_filters = prop_filters
        if return_props is not None:
            self.return_props = return_props

    @property
    def prop_filters(self):
        """Gets the prop_filters of this VertexMatchRule.  # noqa: E501


        :return: The prop_filters of this VertexMatchRule.  # noqa: E501
        :rtype: list[PropertyFilter]
        """
        return self._prop_filters

    @prop_filters.setter
    def prop_filters(self, prop_filters):
        """Sets the prop_filters of this VertexMatchRule.


        :param prop_filters: The prop_filters of this VertexMatchRule.  # noqa: E501
        :type: list[PropertyFilter]
        """

        self._prop_filters = prop_filters

    @property
    def return_props(self):
        """Gets the return_props of this VertexMatchRule.  # noqa: E501


        :return: The return_props of this VertexMatchRule.  # noqa: E501
        :rtype: list[str]
        """
        return self._return_props

    @return_props.setter
    def return_props(self, return_props):
        """Sets the return_props of this VertexMatchRule.


        :param return_props: The return_props of this VertexMatchRule.  # noqa: E501
        :type: list[str]
        """

        self._return_props = return_props

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VertexMatchRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VertexMatchRule):
            return True

        return self.to_dict() != other.to_dict()
