# -*- coding: utf-8 -*-
# Copyright 2023 Ant Group CO., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class Finance:
    
    class AdministrativeArea(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        description = PropertyHelper("description")
        alias = PropertyHelper("alias")
    
    
    
    class AreaRiskEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        id = PropertyHelper("id")
        subject = PropertyHelper("subject")
        eventTime = PropertyHelper("eventTime")
        description = PropertyHelper("description")
        object = PropertyHelper("object")
    
    
    
    class Company(SPGTypeHelper):
        
    
        regArea = PropertyHelper("regArea")
        name = PropertyHelper("name")
        businessScope = PropertyHelper("businessScope")
        id = PropertyHelper("id")
        regCapital = PropertyHelper("regCapital")
        description = PropertyHelper("description")
        legalPerson = PropertyHelper("legalPerson")
        orgCertNo = PropertyHelper("orgCertNo")
        establishDate = PropertyHelper("establishDate")
    
    
    
    class CompanyEvent(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        location = PropertyHelper("location")
        id = PropertyHelper("id")
        happenedTime = PropertyHelper("happenedTime")
        subject = PropertyHelper("subject")
        eventTime = PropertyHelper("eventTime")
        description = PropertyHelper("description")
        object = PropertyHelper("object")
    
    
    
    class Indicator(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        description = PropertyHelper("description")
        alias = PropertyHelper("alias")
    
    
    
    class State(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        id = PropertyHelper("id")
        stdId = PropertyHelper("stdId")
        description = PropertyHelper("description")
        alias = PropertyHelper("alias")
    
        derivedFrom = RelationHelper("derivedFrom")
        causes = RelationHelper("causes")
    
    
    AdministrativeArea = AdministrativeArea("Finance.AdministrativeArea")
    AreaRiskEvent = AreaRiskEvent("Finance.AreaRiskEvent")
    Company = Company("Finance.Company")
    CompanyEvent = CompanyEvent("Finance.CompanyEvent")
    Indicator = Indicator("Finance.Indicator")
    State = State("Finance.State")
    
    pass