INSERT INTO kg_biz_domain (`id`,`gmt_create`,`gmt_modified`,`name`,`status`,`description`,`global_config`) VALUES(1,'2023-09-01 00:00:00','2023-09-01 00:00:00','defaultTenant','VALID','',null);
INSERT INTO kg_project_info (`id`,`name`,`description`,`status`,`gmt_create`,`gmt_modified`,`namespace`,`biz_domain_id`) VALUES(1,'defaultProject','defaultProject','VALID','2023-09-01 00:00:00','2023-09-01 00:00:00','DEFAULT',1);

INSERT INTO kg_data_source (`id`,`gmt_create`,`gmt_modified`,`unique_name`,`type`,`conn_info`,`physical_info`) VALUES(1,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_tugraph','GRAPH_STORE','{"scheme":"tugraph","params":{"graphName":"default","timeout":5000,"host":"127.0.0.1:9090","accessId":"admin","accessKey":"73@TuGraph"}}',null);
INSERT INTO kg_data_source (`id`,`gmt_create`,`gmt_modified`,`unique_name`,`type`,`conn_info`,`physical_info`) VALUES(2,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_operator','OBJECT_STORE','{"scheme":"local","params":{"localDir":"/objectStore/operator"}}',null);
INSERT INTO kg_data_source (`id`,`gmt_create`,`gmt_modified`,`unique_name`,`type`,`conn_info`,`physical_info`) VALUES(3,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_tmpfile','OBJECT_STORE','{"scheme":"local","params":{"localDir":"/objectStore/tmpfile"}}',null);
INSERT INTO kg_data_source (`id`,`gmt_create`,`gmt_modified`,`unique_name`,`type`,`conn_info`,`physical_info`) VALUES(4,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_elasticsearch','SEARCH_ENGINE','{"scheme":"elasticsearch","params":{"host":"127.0.0.1","scheme":"http","port":"9200"}}',null);
INSERT INTO kg_data_source_usage (`id`,`gmt_create`,`gmt_modified`,`data_source_name`,`usage_type`,`is_default`,`mount_object_id`,`mount_object_type`) VALUES(1,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_tugraph','KG_STORE',1,'1','PROJECT');
INSERT INTO kg_data_source_usage (`id`,`gmt_create`,`gmt_modified`,`data_source_name`,`usage_type`,`is_default`,`mount_object_id`,`mount_object_type`) VALUES(2,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_operator','OPERATOR_STORE',1,'-1','PROJECT');
INSERT INTO kg_data_source_usage (`id`,`gmt_create`,`gmt_modified`,`data_source_name`,`usage_type`,`is_default`,`mount_object_id`,`mount_object_type`) VALUES(3,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_tmpfile','FILE_STORE',1,'-1','PROJECT');
INSERT INTO kg_data_source_usage (`id`,`gmt_create`,`gmt_modified`,`data_source_name`,`usage_type`,`is_default`,`mount_object_id`,`mount_object_type`) VALUES(4,'2023-09-01 00:00:00','2023-09-01 00:00:00','local_elasticsearch','SEARCH',1,'1','PROJECT');

INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(1000,1000,'Thing','事物','ADVANCED','EXTENSION','Base class for all schema types, all of which inherit the type either directly or indirectly','所有schema类型的基类，它们都直接或者间接继承该类型','1','TRUE','PUBLIC',44,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,null,'Thing');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(2000,2000,'Text','文本','BASIC','CORE','Data type: Text','基本数据类型-文本','1','TRUE','PUBLIC',0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"REQUIRE","name":"Required","nameZh":"值非空","value":null},{"id":"UNIQUE","name":"Unique","nameZh":"值唯一","value":null},{"id":"ENUM","name":"Enum","nameZh":"枚举","value":null},{"id":"MULTIVALUE","name":"Multi value","nameZh":"多值","value":null},{"id":"REGULAR","name":"Regular match","nameZh":"正则匹配","value":null}]}','Text');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(2001,2001,'Integer','整型','BASIC','CORE','Data type: Integer','基本数据类型-整型','1','TRUE','PUBLIC',0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"REQUIRE","name":"Required","nameZh":"值非空","value":null},{"id":"ENUM","name":"Enum","nameZh":"枚举","value":null},{"id":"MINIMUM_GT","name":"Greater than","nameZh":"大于","value":null},{"id":"MINIMUM_GT_OE","name":"Greater than or equal","nameZh":"大于等于","value":null},{"id":"MAXIMUM_LT","name":"Less than","nameZh":"小于","value":null},{"id":"MAXIMUM_LT_OE","name":"Less than or equal","nameZh":"小于等于","value":null}]}','Integer');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(2002,2002,'Float','浮点数','BASIC','CORE','Data type: Float','基本数据类型-浮点数','1','TRUE','PUBLIC',0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"REQUIRE","name":"Required","nameZh":"值非空","value":null},{"id":"ENUM","name":"Enum","nameZh":"枚举","value":null},{"id":"MINIMUM_GT","name":"Greater than","nameZh":"大于","value":null},{"id":"MINIMUM_GT_OE","name":"Greater than or equal","nameZh":"大于等于","value":null},{"id":"MAXIMUM_LT","name":"Less than","nameZh":"小于","value":null},{"id":"MAXIMUM_LT_OE","name":"Less than or equal","nameZh":"小于等于","value":null}]}','Float');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(3000,3000,'STD.ChinaMobile','国内手机号','STANDARD','CORE','Data type:ChinaMobile','标准类型-国内手机号','1','FALSE',null,0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"MULTIVALUE","name":"Multi value","nameZh":"多值","value":null},{"id":"REGULAR","name":"Regular match","nameZh":"正则匹配","value":"^((13[0-9])|(14[5,7,9])|(15([0-3]|[5-9]))|(16[5,6])|(17[0-8])|(18[0-9])|(19[1,5,8,9]))[0-9]{8}$"}],"spreadable":true}','STD.ChinaMobile');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(3001,3001,'STD.Email','邮箱','STANDARD','CORE','Data type:Email','标准类型-邮箱','1','FALSE',null,0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"MULTIVALUE","name":"Multi value","nameZh":"多值","value":null},{"id":"REGULAR","name":"Regular match","nameZh":"正则匹配","value":"^([a-zA-Z0-9]*[-_.]?[a-zA-Z0-9]+)*@([a-zA-Z0-9]*[-_]?[a-zA-Z0-9]+)+[.][A-Za-z]{2,3}([.][A-Za-z]{2})?$"}],"spreadable":true}','STD.Email');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(3002,3002,'STD.Gender','性别','STANDARD','CORE','Data type:Gender','标准类型-性别','1','FALSE',null,0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"ENUM","name":"Enum","nameZh":"u679Au4E3E","value":{"男":"男","女":"女"}}]}','STD.Gender');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(3003,3003,'STD.Boolean','布尔','STANDARD','CORE','Data type:Boolean','标准类型-布尔','1','FALSE',null,0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"ENUM","name":"Enum","nameZh":"u679Au4E3E","value":{"true":"true","false":"false"}}]}','STD.Boolean');
INSERT INTO kg_ontology_entity (`id`,`original_id`,`name`,`name_zh`,`entity_category`,`layer`,`description`,`description_zh`,`status`,`with_index`,`scope`,`version`,`version_status`,`gmt_create`,`gmt_modified`,`transformer_id`,`operator_config`,`config`,`unique_name`) VALUES(3004,3004,'STD.Timestamp','时间戳','STANDARD','CORE','Data type:Timestamp','标准类型-时间戳','1','FALSE',null,0,'ONLINE','2023-09-01 00:00:00','2023-09-01 00:00:00',0,null,'{"constrains":[{"id":"MINIMUM_GT", "name":"Greater than", "nameZh":"大于", "value":"31507200000"}]}','STD.Timestamp');

INSERT INTO kg_ontology_entity_parent (`id`,`entity_id`,`parent_id`,`status`,`gmt_create`,`gmt_modified`,`path`,`deep_inherit`,`history_path`) VALUES(1,3000,1000,1,'2023-09-01 00:00:00','2023-09-01 00:00:00','1000,3000','N', null);
INSERT INTO kg_ontology_entity_parent (`id`,`entity_id`,`parent_id`,`status`,`gmt_create`,`gmt_modified`,`path`,`deep_inherit`,`history_path`) VALUES(2,3001,1000,1,'2023-09-01 00:00:00','2023-09-01 00:00:00','1000,3001','N', null);
INSERT INTO kg_ontology_entity_parent (`id`,`entity_id`,`parent_id`,`status`,`gmt_create`,`gmt_modified`,`path`,`deep_inherit`,`history_path`) VALUES(3,3002,1000,1,'2023-09-01 00:00:00','2023-09-01 00:00:00','1000,3002','N', null);
INSERT INTO kg_ontology_entity_parent (`id`,`entity_id`,`parent_id`,`status`,`gmt_create`,`gmt_modified`,`path`,`deep_inherit`,`history_path`) VALUES(4,3003,1000,1,'2023-09-01 00:00:00','2023-09-01 00:00:00','1000,3003','N', null);
INSERT INTO kg_ontology_entity_parent (`id`,`entity_id`,`parent_id`,`status`,`gmt_create`,`gmt_modified`,`path`,`deep_inherit`,`history_path`) VALUES(5,3004,1000,1,'2023-09-01 00:00:00','2023-09-01 00:00:00','1000,3004','N', null);

INSERT INTO kg_ontology_entity_property_range (`id`,`domain_id`,`property_name`,`range_id`,`property_name_zh`,`constraint_id`,`property_category`,`map_type`,`version`,`status`,`gmt_create`,`gmt_modified`,`original_id`,`store_property_name`,`transformer_id`,`property_desc`,`property_desc_zh`,`project_id`,`original_domain_id`,`original_range_id`,`version_status`,`relation_source`,`direction`,`mask_type`,`multiver_config`,`property_source`,`property_config`) VALUES(1,1000,'description',2000,'描述',0,'BASIC','TYPE',44,'1','2022-03-21 19:24:54','2023-08-27 09:39:04',1,'description',0,null,null,0,1000,2000,'ONLINE',null,null,null,null,null,null);
INSERT INTO kg_ontology_entity_property_range (`id`,`domain_id`,`property_name`,`range_id`,`property_name_zh`,`constraint_id`,`property_category`,`map_type`,`version`,`status`,`gmt_create`,`gmt_modified`,`original_id`,`store_property_name`,`transformer_id`,`property_desc`,`property_desc_zh`,`project_id`,`original_domain_id`,`original_range_id`,`version_status`,`relation_source`,`direction`,`mask_type`,`multiver_config`,`property_source`,`property_config`) VALUES(2,1000,'id',2000,'实体主键',0,'BASIC','TYPE',44,'1','2022-03-21 19:24:54','2023-08-27 09:39:04',2,'id',0,null,null,0,1000,2000,'ONLINE',null,null,null,null,null,null);
INSERT INTO kg_ontology_entity_property_range (`id`,`domain_id`,`property_name`,`range_id`,`property_name_zh`,`constraint_id`,`property_category`,`map_type`,`version`,`status`,`gmt_create`,`gmt_modified`,`original_id`,`store_property_name`,`transformer_id`,`property_desc`,`property_desc_zh`,`project_id`,`original_domain_id`,`original_range_id`,`version_status`,`relation_source`,`direction`,`mask_type`,`multiver_config`,`property_source`,`property_config`) VALUES(3,1000,'name',2000,'名称',0,'BASIC','TYPE',44,'1','2022-03-21 19:24:54','2023-08-27 09:39:04',3,'name',0,null,null,0,1000,2000,'ONLINE',null,null,null,null,null,null);
