# -*- coding: utf-8 -*-
# Copyright 2023 Ant Group CO., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class TEST:
    
    class CenterEvent(SPGTypeHelper):
        class conceptProperty(PropertyHelper):
            source = PropertyHelper("source")
        
        class eventRelation(RelationHelper):
            source = PropertyHelper("source")
            confidence = PropertyHelper("confidence")
        conceptProperty = conceptProperty("conceptProperty")
    
        basicTextProperty = PropertyHelper("basicTextProperty")
        basicIntegerProperty = PropertyHelper("basicIntegerProperty")
        subject = PropertyHelper("subject")
        id = PropertyHelper("id")
        basicFloatProperty = PropertyHelper("basicFloatProperty")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        standardProperty = PropertyHelper("standardProperty")
        eventTime = PropertyHelper("eventTime")
    
    
        eventRelation = eventRelation("eventRelation")
    
    class Concept1(SPGTypeHelper):
        
    
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
    
        leadTo = RelationHelper("leadTo")
    
    
    class Concept2(SPGTypeHelper):
        
    
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
    
    
    
    class Concept3(SPGTypeHelper):
        
    
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        description = PropertyHelper("description")
    
    
    
    class Entity1(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
    
        predictRelation = RelationHelper("predictRelation")
        entityRelation = RelationHelper("entityRelation")
    
    
    class Entity2(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
    
    
    
    class Entity3(SPGTypeHelper):
        
    
        name = PropertyHelper("name")
        description = PropertyHelper("description")
        id = PropertyHelper("id")
    
    
    
    CenterEvent = CenterEvent("TEST.CenterEvent")
    Concept1 = Concept1("TEST.Concept1")
    Concept2 = Concept2("TEST.Concept2")
    Concept3 = Concept3("TEST.Concept3")
    Entity1 = Entity1("TEST.Entity1")
    Entity2 = Entity2("TEST.Entity2")
    Entity3 = Entity3("TEST.Entity3")
    
    pass